### ISSUE TITLE
执行wokoo my_app报错，只生成一个package.json文件

### ISSUE THREAD

**Issue by WertherHu** [kinyaying/wokoo#3]
wokoo@0.3.1
Node.js v16.10.0

执行wokoo my_app时出现错误。

```
Installing packages. This might take a couple of minutes
Installing wokoo-template ...
npm ERR! No workspaces found:
npm ERR!   --workspace=--loglevel

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\werther\AppData\Local\npm-cache\_logs\2021-10-06T15_43_56_352Z-debug.log
Installing wokoo-template succeed!
? which template do you prefer? vue
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'wokoo-template/package.json'
Require stack:
- C:\Users\werther\anaconda3\node_modules\wokoo\index.js
- C:\Users\werther\anaconda3\node_modules\wokoo\bin\www
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at run (C:\Users\werther\anaconda3\node_modules\wokoo\index.js:84:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createApp (C:\Users\werther\anaconda3\node_modules\wokoo\index.js:50:3)
    at async init (C:\Users\werther\anaconda3\node_modules\wokoo\index.js:22:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\werther\\anaconda3\\node_modules\\wokoo\\index.js',
    'C:\\Users\\werther\\anaconda3\\node_modules\\wokoo\\bin\\www'
  ]
}

```

**Comment by wuyunjiang** [comment]
我也是
![image](https://user-images.githubusercontent.com/16558218/140959142-d6aa1d25-890e-4ec9-a350-789673ca72b6.png)

**Comment by kinyaying** [comment]
是高版本的npm不支持--cwd命令导致的，已经修复了。修复的commit是[41adb0f5dc3ebe562413d3154569484e9fca4a22](https://github.com/kinyaying/wokoo/commit/41adb0f5dc3ebe562413d3154569484e9fca4a22)。 
下载新包即可，谢谢支持
